/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	database_payments "template_backend/database/paths/payments"
	database_rent_contract "template_backend/database/paths/rent_contract"
	database_user "template_backend/database/paths/user"
	"template_backend/infrastructure/payment"
	paymentTypes "template_backend/infrastructure/payment/types"
	openapi "template_backend/open-api/authentication"
	models "template_backend/open-api/models"

	"github.com/rs/zerolog/log"
)

// AdministrationAPIServicer defines the api actions for the AdministrationAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AdministrationAPIServicer interface {
	AdministrationChangeRoleUserIdPost(context.Context, string, models.ChangeRole, *http.Request) (models.ImplResponse, error)
	AdministrationRefundDepositPost(context.Context, models.RefundDeposit, *http.Request) (models.ImplResponse, error)
	AdministrationSalesGet(context.Context, *http.Request) (models.ImplResponse, error)
	AdministrationUsersGet(context.Context, *http.Request) (models.ImplResponse, error)
}

// AdministrationAPIRouter defines the required methods for binding the api requests to a responses for the AdministrationAPI
// The AdministrationAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AdministrationAPIServicer to perform the required actions, then write the service results to the http response.
type AdministrationAPIRouter interface {
	AdministrationChangeRoleUserIdPost(http.ResponseWriter, *http.Request)
	AdministrationRefundDepositPost(http.ResponseWriter, *http.Request)
	AdministrationSalesGet(http.ResponseWriter, *http.Request)
	AdministrationUsersGet(http.ResponseWriter, *http.Request)
}

// AdministrationAPIService is a service that implements the logic for the AdministrationAPIServicer
// This service should implement the business logic for every endpoint for the AdministrationAPI API.
// Include any external packages or services that will be required by this service.
type AdministrationAPIService struct {
}

// NewAdministrationAPIService creates a default api service
func NewAdministrationAPIService() AdministrationAPIServicer {
	return &AdministrationAPIService{}
}

// AdministrationChangeRoleUserIdPost - Change role of an user
func (s *AdministrationAPIService) AdministrationChangeRoleUserIdPost(ctx context.Context, userId string, changeRole models.ChangeRole, r *http.Request) (models.ImplResponse, error) {
	admin, err := openapi.IsAdmin(ctx, r)
	if err != nil || admin == nil {
		return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "100", Message: "Unauthorized"}}}), nil
	}

	user := database_user.FindUserById(ctx, &userId)
	if user == nil {
		return models.Response(404, models.Error{ErrorMessages: []models.Message{{Code: "101", Message: "User not found"}}}), nil
	}

	// Store previous state for rollback
	previousRole := user.Roles
	nextRoles := database_user.RoleMapping(changeRole.Role)

	if previousRole == database_user.ConfirmedUser && nextRoles == database_user.TemporaryUser {
		_, err = database_user.UpdateUserForPayment(ctx, &userId, &nextRoles, nil)
		if err != nil {
			log.Error().Err(err).Msg("Failed to update user role")
			return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "001", Message: "Failed to update user role"}}}), nil
		}

		// Then delete customer
		if user.CustomerIdentifier != nil && user.CustomerIdentifier.ID != "" {
			_, err := payment.DeleteCustomer(user.CustomerIdentifier.ID)
			if err != nil {
				// Rollback user role
				log.Error().Err(err).Msg("Failed to delete customer")
				_, rollbackErr := database_user.UpdateUserForPayment(ctx, &userId, &previousRole, user.CustomerIdentifier)
				if rollbackErr != nil {
					log.Error().Err(rollbackErr).Msg("Failed to rollback user role after payment deletion failure")
				}

				return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "001", Message: "Failed to delete customer"}}}), nil
			}
		}

		return models.Response(200, models.Success{}), nil
	}

	// Handle role change from TemporaryUser to ConfirmedUser
	if previousRole == database_user.TemporaryUser && nextRoles == database_user.ConfirmedUser {
		customerData := payment.CustomerData{
			Email: user.Email,
			Name:  user.Email,
		}
		customer, err := payment.CreateCustomer(customerData)
		if err != nil {
			log.Error().Err(err).Msg("Failed to create customer")
			return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "001", Message: "Failed to create customer"}}}), nil
		}

		customerIdentifier := paymentTypes.CustomerIdentifier{
			ID: customer.ID,
		}
		_, err = database_user.UpdateUserForPayment(ctx, &userId, &nextRoles, &customerIdentifier)
		if err != nil {
			// Rollback customer creation
			if customer != nil {
				_, deleteErr := payment.DeleteCustomer(customer.ID)
				if deleteErr != nil {
					log.Error().Err(deleteErr).Msg("Failed to rollback customer creation")
				}
			}
			log.Error().Err(err).Msg("Failed to enable user for payment")
			return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "001", Message: "Failed to enable user for payment"}}}), nil
		}

		return models.Response(200, models.Success{}), nil
	}

	// Handle other role changes
	_, err = database_user.UpdateUserForPayment(ctx, &userId, &nextRoles, user.CustomerIdentifier)
	if err != nil {
		log.Error().Err(err).Msg("Failed to update user role")
		return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "001", Message: "Failed to update user role"}}}), nil
	}

	return models.Response(200, models.Success{}), nil
}

// AdministrationRefundDepositPost - Refund deposit of a payment transaction
func (s *AdministrationAPIService) AdministrationRefundDepositPost(ctx context.Context, refundDeposit models.RefundDeposit, r *http.Request) (models.ImplResponse, error) {
	admin, err := openapi.IsAdmin(ctx, r)
	if err != nil || admin == nil {
		return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "100", Message: "Unauthorized"}}}), nil
	}

	rentContract := database_rent_contract.FindRentContractByPaymentTransactionId(ctx, refundDeposit.PaymentTransactionId)
	if rentContract == nil {
		return models.Response(404, models.Error{ErrorMessages: []models.Message{{Code: "101", Message: "Rent contract not found"}}}), nil
	}

	_, err = payment.RefundPrice(rentContract.PaymentIdentifier.PaymentIntent, refundDeposit.DepositRefundedAmount)
	if err != nil {
		log.Error().Err(err).Msg("Failed to refund price")
		return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "001", Message: "Failed to refund price"}}}), nil
	}

	_, err = database_payments.RefundDepositPaymentTransaction(ctx, refundDeposit.PaymentTransactionId, refundDeposit.DepositRefundedAmount)
	if err != nil {
		log.Error().Err(err).Msg("Failed to refund deposit")
		return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "001", Message: "Failed to refund deposit"}}}), nil
	}

	return models.Response(200, models.Success{}), nil
}

// AdministrationSalesGet - Retrieve all sales
func (s *AdministrationAPIService) AdministrationSalesGet(ctx context.Context, r *http.Request) (models.ImplResponse, error) {
	admin, err := openapi.IsAdmin(ctx, r)
	if err != nil || admin == nil {
		return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "100", Message: "Unauthorized"}}}), nil
	}

	paymentTransactions := database_payments.GetAllPaymentTransactions(ctx)
	sanitizedPaymentTransactions := make([]models.Sale, len(paymentTransactions))
	for i, paymentTransaction := range paymentTransactions {
		sanitizedPaymentTransactions[i] = models.Sale{
			Id:                    paymentTransaction.ID,
			ProductId:             paymentTransaction.ProductID,
			UserId:                paymentTransaction.CustomerID,
			Price:                 paymentTransaction.ProductPrice,
			Paid:                  paymentTransaction.Paid,
			Deposit:               paymentTransaction.ProductDeposit,
			CreatedAt:             paymentTransaction.CreatedAt,
			PaidAt:                paymentTransaction.PaidAt,
			ReturnedAt:            paymentTransaction.ReturnedAt,
			DepositRefundedAmount: paymentTransaction.DepositRefundedAmount,
			DepositRefundedAt:     paymentTransaction.DepositRefundedAt,
		}
	}
	return models.Response(200, sanitizedPaymentTransactions), nil
}

// AdministrationUsersGet - Get all users
func (s *AdministrationAPIService) AdministrationUsersGet(ctx context.Context, r *http.Request) (models.ImplResponse, error) {
	admin, err := openapi.IsAdmin(ctx, r)
	if err != nil || admin == nil {
		return models.Response(401, models.Error{ErrorMessages: []models.Message{{Code: "100", Message: "Unauthorized"}}}), nil
	}

	users := database_user.GetAllUsers(ctx)
	sanitizedUsers := make([]database_user.PublicUserProfile, len(users))
	for i, user := range users {
		sanitizedUsers[i] = *database_user.SanitizeUserProfileForAdmin(&user)
	}
	return models.Response(200, sanitizedUsers), nil
}
