services:
  proxy:
    container_name: ${APP_NAME}_nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      - host_network
    env_file:
      - ./environment/dev/nginx.env
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 10s
    ports:
      - '80:80'
      - '3000:81'
      - '443:443'
    volumes:
      - ./dockerfiles/nginx:/data
    depends_on:
      - mawida_ui
      - mawida_backend
      - mawida_database
    profiles:
      - local
  mawida_ui:
    container_name: ${APP_NAME}_ui
    build:
      context: .
      dockerfile: ./dockerfiles/ui.Dockerfile
    restart: unless-stopped
    networks:
      - host_network
    volumes:
      - ./src/ui/src:/src/src
    environment:
      - app_env=${docker_env}
    env_file:
      - ./environment/global.env
    profiles:
      - local
      - deployment
  mawida_backend:
    container_name: ${APP_NAME}_backend
    build:
      context: .
      dockerfile: ./dockerfiles/backend.Dockerfile
    restart: unless-stopped
    networks:
      - host_network
    volumes:
      - ./src/backend:/app
    environment:
      - app_env=${docker_env}
    env_file:
      - ./environment/global.env
    depends_on:
      - mawida_database
    profiles:
      - local
      - deployment
  mawida_database:
    container_name: ${APP_NAME}_db
    build:
      context: .
      dockerfile: ./dockerfiles/database.Dockerfile
    restart: always
    environment:
      - app_env=${docker_env}
    env_file:
      - ./environment/global.env
    logging:
      driver: none
    attach: false
    volumes:
        - ./dockerfiles/db:/opt/couchdb/data
    networks:
      - host_network
    profiles:
      - local
      - deployment

networks:
  host_network:
    external: true
