/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeRole
 */
export interface ChangeRole {
    /**
     * Role to change to
     * @type {string}
     * @memberof ChangeRole
     */
    role: ChangeRoleRoleEnum;
}


/**
 * @export
 */
export const ChangeRoleRoleEnum = {
    Admin: 'admin',
    User: 'user',
    Unverified: 'unverified'
} as const;
export type ChangeRoleRoleEnum = typeof ChangeRoleRoleEnum[keyof typeof ChangeRoleRoleEnum];


/**
 * Check if a given object implements the ChangeRole interface.
 */
export function instanceOfChangeRole(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function ChangeRoleFromJSON(json: any): ChangeRole {
    return ChangeRoleFromJSONTyped(json, false);
}

export function ChangeRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': json['role'],
    };
}

export function ChangeRoleToJSON(value?: ChangeRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': value.role,
    };
}

