/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Coordinates and notes for the product location
 * @export
 * @interface LocationCoordinates
 */
export interface LocationCoordinates {
    /**
     * Latitude of the product location
     * @type {number}
     * @memberof LocationCoordinates
     */
    latitude?: number;
    /**
     * Longitude of the product location
     * @type {number}
     * @memberof LocationCoordinates
     */
    longitude?: number;
    /**
     * Additional notes or annotations about the coordinates
     * @type {string}
     * @memberof LocationCoordinates
     */
    notes?: string;
}

/**
 * Check if a given object implements the LocationCoordinates interface.
 */
export function instanceOfLocationCoordinates(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LocationCoordinatesFromJSON(json: any): LocationCoordinates {
    return LocationCoordinatesFromJSONTyped(json, false);
}

export function LocationCoordinatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationCoordinates {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function LocationCoordinatesToJSON(value?: LocationCoordinates | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
        'notes': value.notes,
    };
}

