/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
} from './PaymentMethod';

/**
 * 
 * @export
 * @interface PaymentInstructions
 */
export interface PaymentInstructions {
    /**
     * Unique identifier for the payment transaction
     * @type {string}
     * @memberof PaymentInstructions
     */
    paymentTransactionId: string;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof PaymentInstructions
     */
    paymentMethodId: PaymentMethod;
    /**
     * Dynamic attributes for the payment instructions
     * @type {{ [key: string]: any; }}
     * @memberof PaymentInstructions
     */
    dynamicAttributes?: { [key: string]: any; };
}

/**
 * Check if a given object implements the PaymentInstructions interface.
 */
export function instanceOfPaymentInstructions(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "paymentTransactionId" in value;
    isInstance = isInstance && "paymentMethodId" in value;

    return isInstance;
}

export function PaymentInstructionsFromJSON(json: any): PaymentInstructions {
    return PaymentInstructionsFromJSONTyped(json, false);
}

export function PaymentInstructionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentInstructions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paymentTransactionId': json['paymentTransactionId'],
        'paymentMethodId': PaymentMethodFromJSON(json['paymentMethodId']),
        'dynamicAttributes': !exists(json, 'dynamicAttributes') ? undefined : json['dynamicAttributes'],
    };
}

export function PaymentInstructionsToJSON(value?: PaymentInstructions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'paymentTransactionId': value.paymentTransactionId,
        'paymentMethodId': PaymentMethodToJSON(value.paymentMethodId),
        'dynamicAttributes': value.dynamicAttributes,
    };
}

