/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PickupConfirmation
 */
export interface PickupConfirmation {
    /**
     * 
     * @type {Array<string>}
     * @memberof PickupConfirmation
     */
    pickupImages: Array<string>;
}

/**
 * Check if a given object implements the PickupConfirmation interface.
 */
export function instanceOfPickupConfirmation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pickupImages" in value;

    return isInstance;
}

export function PickupConfirmationFromJSON(json: any): PickupConfirmation {
    return PickupConfirmationFromJSONTyped(json, false);
}

export function PickupConfirmationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupConfirmation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pickupImages': json['pickupImages'],
    };
}

export function PickupConfirmationToJSON(value?: PickupConfirmation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pickupImages': value.pickupImages,
    };
}

