/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Product } from './Product';
import {
    instanceOfProduct,
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';
import type { ProductPublic } from './ProductPublic';
import {
    instanceOfProductPublic,
    ProductPublicFromJSON,
    ProductPublicFromJSONTyped,
    ProductPublicToJSON,
} from './ProductPublic';

/**
 * @type ProductsProductIdGet200Response
 * 
 * @export
 */
export type ProductsProductIdGet200Response = Product | ProductPublic;

export function ProductsProductIdGet200ResponseFromJSON(json: any): ProductsProductIdGet200Response {
    return ProductsProductIdGet200ResponseFromJSONTyped(json, false);
}

export function ProductsProductIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsProductIdGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ProductFromJSONTyped(json, true), ...ProductPublicFromJSONTyped(json, true) };
}

export function ProductsProductIdGet200ResponseToJSON(value?: ProductsProductIdGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfProduct(value)) {
        return ProductToJSON(value as Product);
    }
    if (instanceOfProductPublic(value)) {
        return ProductPublicToJSON(value as ProductPublic);
    }

    return {};
}

