/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the rental period
 * @export
 * @interface ProductPublicAllOfRenterInfo
 */
export interface ProductPublicAllOfRenterInfo {
    /**
     * Unix timestamp for the start date of the rental period
     * @type {number}
     * @memberof ProductPublicAllOfRenterInfo
     */
    rentalStartDate?: number;
    /**
     * Unix timestamp for the end date of the rental period
     * @type {number}
     * @memberof ProductPublicAllOfRenterInfo
     */
    rentalEndDate?: number;
    /**
     * Expected duration of the rental
     * @type {string}
     * @memberof ProductPublicAllOfRenterInfo
     */
    expectedDuration?: string;
}

/**
 * Check if a given object implements the ProductPublicAllOfRenterInfo interface.
 */
export function instanceOfProductPublicAllOfRenterInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductPublicAllOfRenterInfoFromJSON(json: any): ProductPublicAllOfRenterInfo {
    return ProductPublicAllOfRenterInfoFromJSONTyped(json, false);
}

export function ProductPublicAllOfRenterInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPublicAllOfRenterInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rentalStartDate': !exists(json, 'rentalStartDate') ? undefined : json['rentalStartDate'],
        'rentalEndDate': !exists(json, 'rentalEndDate') ? undefined : json['rentalEndDate'],
        'expectedDuration': !exists(json, 'expectedDuration') ? undefined : json['expectedDuration'],
    };
}

export function ProductPublicAllOfRenterInfoToJSON(value?: ProductPublicAllOfRenterInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rentalStartDate': value.rentalStartDate,
        'rentalEndDate': value.rentalEndDate,
        'expectedDuration': value.expectedDuration,
    };
}

