/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Pricing details including price and deposit
 * @export
 * @interface ProductPricing
 */
export interface ProductPricing {
    /**
     * Price of the product
     * @type {number}
     * @memberof ProductPricing
     */
    price: number;
    /**
     * Deposit amount for the product
     * @type {number}
     * @memberof ProductPricing
     */
    deposit?: number;
}

/**
 * Check if a given object implements the ProductPricing interface.
 */
export function instanceOfProductPricing(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "price" in value;

    return isInstance;
}

export function ProductPricingFromJSON(json: any): ProductPricing {
    return ProductPricingFromJSONTyped(json, false);
}

export function ProductPricingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPricing {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'price': json['price'],
        'deposit': !exists(json, 'deposit') ? undefined : json['deposit'],
    };
}

export function ProductPricingToJSON(value?: ProductPricing | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'price': value.price,
        'deposit': value.deposit,
    };
}

