/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductDocumentsInner } from './ProductDocumentsInner';
import {
    ProductDocumentsInnerFromJSON,
    ProductDocumentsInnerFromJSONTyped,
    ProductDocumentsInnerToJSON,
} from './ProductDocumentsInner';
import type { ProductImagesInner } from './ProductImagesInner';
import {
    ProductImagesInnerFromJSON,
    ProductImagesInnerFromJSONTyped,
    ProductImagesInnerToJSON,
} from './ProductImagesInner';
import type { ProductPricing } from './ProductPricing';
import {
    ProductPricingFromJSON,
    ProductPricingFromJSONTyped,
    ProductPricingToJSON,
} from './ProductPricing';
import type { ProductPublicAllOfRenterInfo } from './ProductPublicAllOfRenterInfo';
import {
    ProductPublicAllOfRenterInfoFromJSON,
    ProductPublicAllOfRenterInfoFromJSONTyped,
    ProductPublicAllOfRenterInfoToJSON,
} from './ProductPublicAllOfRenterInfo';

/**
 * 
 * @export
 * @interface ProductPublic
 */
export interface ProductPublic {
    /**
     * Unique identifier for the product
     * @type {string}
     * @memberof ProductPublic
     */
    id?: string;
    /**
     * Name of the product
     * @type {string}
     * @memberof ProductPublic
     */
    name: string;
    /**
     * Description of the product
     * @type {string}
     * @memberof ProductPublic
     */
    description: string;
    /**
     * List of base64 encoded image data with IDs and names
     * @type {Array<ProductImagesInner>}
     * @memberof ProductPublic
     */
    images?: Array<ProductImagesInner>;
    /**
     * List of base64 encoded document data with IDs and names
     * @type {Array<ProductDocumentsInner>}
     * @memberof ProductPublic
     */
    documents?: Array<ProductDocumentsInner>;
    /**
     * Location ID of the product
     * @type {string}
     * @memberof ProductPublic
     */
    location: string;
    /**
     * 
     * @type {ProductPricing}
     * @memberof ProductPublic
     */
    pricing: ProductPricing;
    /**
     * Dynamic attributes for the product
     * @type {{ [key: string]: any; }}
     * @memberof ProductPublic
     */
    dynamicAttributes?: { [key: string]: any; };
    /**
     * Indicates whether the product is currently rented
     * @type {boolean}
     * @memberof ProductPublic
     */
    isRented?: boolean;
    /**
     * Indicates whether the current user is the renter of the product
     * @type {boolean}
     * @memberof ProductPublic
     */
    isCurrentUserRenter?: boolean;
    /**
     * URL of the generated QR code
     * @type {string}
     * @memberof ProductPublic
     */
    qrCodeUrl?: string;
    /**
     * 
     * @type {ProductPublicAllOfRenterInfo}
     * @memberof ProductPublic
     */
    renterInfo?: ProductPublicAllOfRenterInfo;
}

/**
 * Check if a given object implements the ProductPublic interface.
 */
export function instanceOfProductPublic(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "location" in value;
    isInstance = isInstance && "pricing" in value;

    return isInstance;
}

export function ProductPublicFromJSON(json: any): ProductPublic {
    return ProductPublicFromJSONTyped(json, false);
}

export function ProductPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPublic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'],
        'images': !exists(json, 'images') ? undefined : ((json['images'] as Array<any>).map(ProductImagesInnerFromJSON)),
        'documents': !exists(json, 'documents') ? undefined : ((json['documents'] as Array<any>).map(ProductDocumentsInnerFromJSON)),
        'location': json['location'],
        'pricing': ProductPricingFromJSON(json['pricing']),
        'dynamicAttributes': !exists(json, 'dynamicAttributes') ? undefined : json['dynamicAttributes'],
        'isRented': !exists(json, 'isRented') ? undefined : json['isRented'],
        'isCurrentUserRenter': !exists(json, 'isCurrentUserRenter') ? undefined : json['isCurrentUserRenter'],
        'qrCodeUrl': !exists(json, 'qrCodeUrl') ? undefined : json['qrCodeUrl'],
        'renterInfo': !exists(json, 'renterInfo') ? undefined : ProductPublicAllOfRenterInfoFromJSON(json['renterInfo']),
    };
}

export function ProductPublicToJSON(value?: ProductPublic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'images': value.images === undefined ? undefined : ((value.images as Array<any>).map(ProductImagesInnerToJSON)),
        'documents': value.documents === undefined ? undefined : ((value.documents as Array<any>).map(ProductDocumentsInnerToJSON)),
        'location': value.location,
        'pricing': ProductPricingToJSON(value.pricing),
        'dynamicAttributes': value.dynamicAttributes,
        'isRented': value.isRented,
        'isCurrentUserRenter': value.isCurrentUserRenter,
        'qrCodeUrl': value.qrCodeUrl,
        'renterInfo': ProductPublicAllOfRenterInfoToJSON(value.renterInfo),
    };
}

