/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductImagesInner
 */
export interface ProductImagesInner {
    /**
     * Unique identifier for the image
     * @type {string}
     * @memberof ProductImagesInner
     */
    id: string;
    /**
     * Name of the image
     * @type {string}
     * @memberof ProductImagesInner
     */
    name: string;
    /**
     * Base64 encoded image data
     * @type {string}
     * @memberof ProductImagesInner
     */
    data: string;
}

/**
 * Check if a given object implements the ProductImagesInner interface.
 */
export function instanceOfProductImagesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ProductImagesInnerFromJSON(json: any): ProductImagesInner {
    return ProductImagesInnerFromJSONTyped(json, false);
}

export function ProductImagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductImagesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'data': json['data'],
    };
}

export function ProductImagesInnerToJSON(value?: ProductImagesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'data': value.data,
    };
}

