/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefundDeposit
 */
export interface RefundDeposit {
    /**
     * Unique identifier for the payment transaction
     * @type {string}
     * @memberof RefundDeposit
     */
    paymentTransactionId?: string;
    /**
     * Amount of the deposit that has been refunded
     * @type {number}
     * @memberof RefundDeposit
     */
    depositRefundedAmount?: number;
}

/**
 * Check if a given object implements the RefundDeposit interface.
 */
export function instanceOfRefundDeposit(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RefundDepositFromJSON(json: any): RefundDeposit {
    return RefundDepositFromJSONTyped(json, false);
}

export function RefundDepositFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundDeposit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paymentTransactionId': !exists(json, 'paymentTransactionId') ? undefined : json['paymentTransactionId'],
        'depositRefundedAmount': !exists(json, 'depositRefundedAmount') ? undefined : json['depositRefundedAmount'],
    };
}

export function RefundDepositToJSON(value?: RefundDeposit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'paymentTransactionId': value.paymentTransactionId,
        'depositRefundedAmount': value.depositRefundedAmount,
    };
}

