/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RentProductFormular
 */
export interface RentProductFormular {
    /**
     * Unique identifier for the user renting the product
     * @type {string}
     * @memberof RentProductFormular
     */
    userId: string;
    /**
     * The start date of the rental period
     * @type {Date}
     * @memberof RentProductFormular
     */
    rentalStartDate: Date;
    /**
     * The end date of the rental period
     * @type {Date}
     * @memberof RentProductFormular
     */
    rentalEndDate: Date;
    /**
     * Free text for additional notes or special instructions
     * @type {string}
     * @memberof RentProductFormular
     */
    additionalNotes?: string;
    /**
     * Identifier for the location where the product will be picked up
     * @type {string}
     * @memberof RentProductFormular
     */
    locationId: string;
    /**
     * Identifier for the payment method used for the rental
     * @type {string}
     * @memberof RentProductFormular
     */
    paymentMethodId: string;
    /**
     * Dynamic attributes for the rental request
     * @type {{ [key: string]: any; }}
     * @memberof RentProductFormular
     */
    dynamicAttributes?: { [key: string]: any; };
}

/**
 * Check if a given object implements the RentProductFormular interface.
 */
export function instanceOfRentProductFormular(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "rentalStartDate" in value;
    isInstance = isInstance && "rentalEndDate" in value;
    isInstance = isInstance && "locationId" in value;
    isInstance = isInstance && "paymentMethodId" in value;

    return isInstance;
}

export function RentProductFormularFromJSON(json: any): RentProductFormular {
    return RentProductFormularFromJSONTyped(json, false);
}

export function RentProductFormularFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentProductFormular {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'rentalStartDate': (new Date(json['rentalStartDate'])),
        'rentalEndDate': (new Date(json['rentalEndDate'])),
        'additionalNotes': !exists(json, 'additionalNotes') ? undefined : json['additionalNotes'],
        'locationId': json['locationId'],
        'paymentMethodId': json['paymentMethodId'],
        'dynamicAttributes': !exists(json, 'dynamicAttributes') ? undefined : json['dynamicAttributes'],
    };
}

export function RentProductFormularToJSON(value?: RentProductFormular | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'rentalStartDate': (value.rentalStartDate.toISOString().substring(0,10)),
        'rentalEndDate': (value.rentalEndDate.toISOString().substring(0,10)),
        'additionalNotes': value.additionalNotes,
        'locationId': value.locationId,
        'paymentMethodId': value.paymentMethodId,
        'dynamicAttributes': value.dynamicAttributes,
    };
}

