/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of the rent contract
 * @export
 */
export const RentContractStatus = {
    PickupPending: 'pickupPending',
    Confirmed: 'confirmed',
    Active: 'active',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;
export type RentContractStatus = typeof RentContractStatus[keyof typeof RentContractStatus];


export function RentContractStatusFromJSON(json: any): RentContractStatus {
    return RentContractStatusFromJSONTyped(json, false);
}

export function RentContractStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentContractStatus {
    return json as RentContractStatus;
}

export function RentContractStatusToJSON(value?: RentContractStatus | null): any {
    return value as any;
}

