/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RentProductConfirmation
 */
export interface RentProductConfirmation {
    /**
     * Unique identifier for the rent contract
     * @type {string}
     * @memberof RentProductConfirmation
     */
    rentContractId?: string;
}

/**
 * Check if a given object implements the RentProductConfirmation interface.
 */
export function instanceOfRentProductConfirmation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RentProductConfirmationFromJSON(json: any): RentProductConfirmation {
    return RentProductConfirmationFromJSONTyped(json, false);
}

export function RentProductConfirmationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RentProductConfirmation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rentContractId': !exists(json, 'rentContractId') ? undefined : json['rentContractId'],
    };
}

export function RentProductConfirmationToJSON(value?: RentProductConfirmation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rentContractId': value.rentContractId,
    };
}

