/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReturnProduct
 */
export interface ReturnProduct {
    /**
     * 
     * @type {Array<string>}
     * @memberof ReturnProduct
     */
    returnImages: Array<string>;
    /**
     * Free text for additional notes or special instructions
     * @type {string}
     * @memberof ReturnProduct
     */
    additionalNotes: string;
}

/**
 * Check if a given object implements the ReturnProduct interface.
 */
export function instanceOfReturnProduct(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "returnImages" in value;
    isInstance = isInstance && "additionalNotes" in value;

    return isInstance;
}

export function ReturnProductFromJSON(json: any): ReturnProduct {
    return ReturnProductFromJSONTyped(json, false);
}

export function ReturnProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'returnImages': json['returnImages'],
        'additionalNotes': json['additionalNotes'],
    };
}

export function ReturnProductToJSON(value?: ReturnProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'returnImages': value.returnImages,
        'additionalNotes': value.additionalNotes,
    };
}

