/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RefundDeposit struct {

	// Unique identifier for the payment transaction
	PaymentTransactionId string `json:"paymentTransactionId,omitempty"`

	// Amount of the deposit that has been refunded
	DepositRefundedAmount int64 `json:"depositRefundedAmount,omitempty"`
}

// AssertRefundDepositRequired checks if the required fields are not zero-ed
func AssertRefundDepositRequired(obj RefundDeposit) error {
	return nil
}

// AssertRefundDepositConstraints checks if the values respects the defined constraints
func AssertRefundDepositConstraints(obj RefundDeposit) error {
	return nil
}
