/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "template_backend/infrastructure/validators"

type Product struct {
	// ID of the product
	ID string `json:"id"`

	// Name of the product
	Name string `json:"name" validate:"required,min=2,max=100"`

	// Description of the product
	Description string `json:"description" validate:"required,min=10,max=1000"`

	// List of base64 encoded image data with IDs and names
	Images []ProductImagesInner `json:"images,omitempty" validate:"omitempty,dive"`

	// List of base64 encoded document data with IDs and names
	Documents []ProductDocumentsInner `json:"documents,omitempty" validate:"omitempty,dive"`

	// Location ID of the product
	Location string `json:"location" validate:"required"`

	Pricing ProductPricing `json:"pricing" validate:"required"`

	// Dynamic attributes for the product
	DynamicAttributes map[string]interface{} `json:"dynamicAttributes,omitempty" validate:"omitempty"`
}

// AssertProductRequired checks if the required fields are not zero-ed
func AssertProductRequired(obj Product) error {
	elements := map[string]interface{}{
		"name":        obj.Name,
		"description": obj.Description,
		"location":    obj.Location,
		"pricing":     obj.Pricing,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Images {
		if err := AssertProductImagesInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Documents {
		if err := AssertProductDocumentsInnerRequired(el); err != nil {
			return err
		}
	}
	if err := AssertProductPricingRequired(obj.Pricing); err != nil {
		return err
	}
	return nil
}

// AssertProductConstraints checks if the values respects the defined constraints
func AssertProductConstraints(obj Product) error {
	return validators.Validate.Struct(obj)
}
