/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "template_backend/infrastructure/validators"

// ProductPricing - Pricing details including price and deposit
type ProductPricing struct {

	// Price of the product
	Price float32 `json:"price" validate:"required,gte=0"`

	// Deposit amount for the product
	Deposit float32 `json:"deposit,omitempty" validate:"omitempty,gte=0"`
}

// AssertProductPricingRequired checks if the required fields are not zero-ed
func AssertProductPricingRequired(obj ProductPricing) error {
	elements := map[string]interface{}{
		"price": obj.Price,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertProductPricingConstraints checks if the values respects the defined constraints
func AssertProductPricingConstraints(obj ProductPricing) error {
	return validators.Validate.Struct(obj)
}
