/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "template_backend/infrastructure/validators"

type PickupConfirmation struct {
	// Base64 encoded image data
	PickupImages []string `json:"pickupImages" validate:"required,max=10,dive,required"`
}

// AssertPickupConfirmationRequired checks if the required fields are not zero-ed
func AssertPickupConfirmationRequired(obj PickupConfirmation) error {
	elements := map[string]interface{}{
		"pickupImages": obj.PickupImages,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPickupConfirmationConstraints checks if the values respects the defined constraints
func AssertPickupConfirmationConstraints(obj PickupConfirmation) error {
	return validators.Validate.Struct(obj)
}
