/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ProductPublicAllOfRenterInfo - Information about the rental period
type ProductPublicAllOfRenterInfo struct {

	// Start date of the rental period
	RentalStartDate string `json:"rentalStartDate,omitempty"`

	// End date of the rental period
	RentalEndDate string `json:"rentalEndDate,omitempty"`

	// Expected duration of the rental
	ExpectedDuration string `json:"expectedDuration,omitempty"`
}

// AssertProductPublicAllOfRenterInfoRequired checks if the required fields are not zero-ed
func AssertProductPublicAllOfRenterInfoRequired(obj ProductPublicAllOfRenterInfo) error {
	return nil
}

// AssertProductPublicAllOfRenterInfoConstraints checks if the values respects the defined constraints
func AssertProductPublicAllOfRenterInfoConstraints(obj ProductPublicAllOfRenterInfo) error {
	return nil
}
