/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"template_backend/infrastructure/validators"
)

type PaymentInstructions struct {
	PaymentTransactionId string `json:"paymentTransactionId"`

	PaymentMethodId PaymentMethod `json:"paymentMethodId"`

	// Dynamic attributes for the payment instructions
	DynamicAttributes map[string]interface{} `json:"dynamicAttributes,omitempty" validate:"dynamicAttributes"`
}

// AssertPaymentInstructionsRequired checks if the required fields are not zero-ed
func AssertPaymentInstructionsRequired(obj PaymentInstructions) error {
	elements := map[string]interface{}{
		"paymentMethodId":      obj.PaymentMethodId,
		"paymentTransactionId": obj.PaymentTransactionId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPaymentInstructionsConstraints checks if the values respects the defined constraints
func AssertPaymentInstructionsConstraints(obj PaymentInstructions) error {
	return validators.Validate.Struct(obj)
}
