/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// AdminAPIService is a service that implements the logic for the AdminAPIServicer
// This service should implement the business logic for every endpoint for the AdminAPI API.
// Include any external packages or services that will be required by this service.
type AdminAPIService struct {
}

// NewAdminAPIService creates a default api service
func NewAdminAPIService() AdminAPIServicer {
	return &AdminAPIService{}
}

// LocationLocationIdGet - Retrieve a single location
func (s *AdminAPIService) LocationLocationIdGet(ctx context.Context, locationId string) (ImplResponse, error) {
	// TODO - update LocationLocationIdGet with the required logic for this service method.
	// Add api_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Location{}) or use other options such as http.Ok ...
	// return Response(200, Location{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("LocationLocationIdGet method not implemented")
}

// LocationsGet - Retrieve all locations
func (s *AdminAPIService) LocationsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update LocationsGet with the required logic for this service method.
	// Add api_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Location{}) or use other options such as http.Ok ...
	// return Response(200, []Location{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("LocationsGet method not implemented")
}

// LocationsPost - Create a new location
func (s *AdminAPIService) LocationsPost(ctx context.Context, location Location) (ImplResponse, error) {
	// TODO - update LocationsPost with the required logic for this service method.
	// Add api_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Success{}) or use other options such as http.Ok ...
	// return Response(201, Success{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("LocationsPost method not implemented")
}

// ProductsGet - Retrieve all products
func (s *AdminAPIService) ProductsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ProductsGet with the required logic for this service method.
	// Add api_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Product{}) or use other options such as http.Ok ...
	// return Response(200, []Product{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProductsGet method not implemented")
}

// ProductsPost - Create a new product
func (s *AdminAPIService) ProductsPost(ctx context.Context, product Product) (ImplResponse, error) {
	// TODO - update ProductsPost with the required logic for this service method.
	// Add api_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Product{}) or use other options such as http.Ok ...
	// return Response(201, Product{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProductsPost method not implemented")
}

// ProductsProductIdGet - Retrieve a single product
func (s *AdminAPIService) ProductsProductIdGet(ctx context.Context, productId string) (ImplResponse, error) {
	// TODO - update ProductsProductIdGet with the required logic for this service method.
	// Add api_admin_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ProductsProductIdGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, ProductsProductIdGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProductsProductIdGet method not implemented")
}
