/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// RentalAPIService is a service that implements the logic for the RentalAPIServicer
// This service should implement the business logic for every endpoint for the RentalAPI API.
// Include any external packages or services that will be required by this service.
type RentalAPIService struct {
}

// NewRentalAPIService creates a default api service
func NewRentalAPIService() RentalAPIServicer {
	return &RentalAPIService{}
}

// ProductsProductIdRentPost - Rent a product
func (s *RentalAPIService) ProductsProductIdRentPost(ctx context.Context, productId string, rentProductFormular RentProductFormular) (ImplResponse, error) {
	// TODO - update ProductsProductIdRentPost with the required logic for this service method.
	// Add api_rental_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, RentProductConfirmation{}) or use other options such as http.Ok ...
	// return Response(200, RentProductConfirmation{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProductsProductIdRentPost method not implemented")
}

// RentalsRentContractIdPickupPost - Confirm product pickup
func (s *RentalAPIService) RentalsRentContractIdPickupPost(ctx context.Context, rentContractId string, pickupConfirmation PickupConfirmation) (ImplResponse, error) {
	// TODO - update RentalsRentContractIdPickupPost with the required logic for this service method.
	// Add api_rental_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Success{}) or use other options such as http.Ok ...
	// return Response(200, Success{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RentalsRentContractIdPickupPost method not implemented")
}

// RentalsRentContractIdReturnPost - Confirm product return
func (s *RentalAPIService) RentalsRentContractIdReturnPost(ctx context.Context, rentContractId string, returnProduct ReturnProduct) (ImplResponse, error) {
	// TODO - update RentalsRentContractIdReturnPost with the required logic for this service method.
	// Add api_rental_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Success{}) or use other options such as http.Ok ...
	// return Response(200, Success{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RentalsRentContractIdReturnPost method not implemented")
}
