/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ReturnProduct struct {

	// Unique identifier for the user returning the product
	UserId string `json:"userId"`

	ReturnImages []string `json:"returnImages"`

	// Free text for additional notes or special instructions
	AdditionalNotes string `json:"additionalNotes"`
}

// AssertReturnProductRequired checks if the required fields are not zero-ed
func AssertReturnProductRequired(obj ReturnProduct) error {
	elements := map[string]interface{}{
		"userId":          obj.UserId,
		"returnImages":    obj.ReturnImages,
		"additionalNotes": obj.AdditionalNotes,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertReturnProductConstraints checks if the values respects the defined constraints
func AssertReturnProductConstraints(obj ReturnProduct) error {
	return nil
}
