/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// LocationCoordinates - Coordinates and notes for the product location
type LocationCoordinates struct {

	// Latitude of the product location
	Latitude float32 `json:"latitude,omitempty"`

	// Longitude of the product location
	Longitude float32 `json:"longitude,omitempty"`

	// Additional notes or annotations about the coordinates
	Notes string `json:"notes,omitempty"`
}

// AssertLocationCoordinatesRequired checks if the required fields are not zero-ed
func AssertLocationCoordinatesRequired(obj LocationCoordinates) error {
	return nil
}

// AssertLocationCoordinatesConstraints checks if the values respects the defined constraints
func AssertLocationCoordinatesConstraints(obj LocationCoordinates) error {
	return nil
}
