/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ProductDocumentsInner struct {

	// Unique identifier for the document
	Id string `json:"id"`

	// Name of the document
	Name string `json:"name"`

	// Base64 encoded document data
	Data string `json:"data"`
}

// AssertProductDocumentsInnerRequired checks if the required fields are not zero-ed
func AssertProductDocumentsInnerRequired(obj ProductDocumentsInner) error {
	elements := map[string]interface{}{
		"id":   obj.Id,
		"name": obj.Name,
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertProductDocumentsInnerConstraints checks if the values respects the defined constraints
func AssertProductDocumentsInnerConstraints(obj ProductDocumentsInner) error {
	return nil
}
