/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Location struct {

	// Unique identifier for the location
	Id string `json:"id,omitempty"`

	// City where the product is located
	City string `json:"city,omitempty"`

	// Street address of the product location
	Street string `json:"street,omitempty"`

	// Postal code of the product location
	PostalCode string `json:"postalCode,omitempty"`

	// Name of the building
	BuildingName string `json:"buildingName,omitempty"`

	Coordinates LocationCoordinates `json:"coordinates,omitempty"`
}

// AssertLocationRequired checks if the required fields are not zero-ed
func AssertLocationRequired(obj Location) error {
	if err := AssertLocationCoordinatesRequired(obj.Coordinates); err != nil {
		return err
	}
	return nil
}

// AssertLocationConstraints checks if the values respects the defined constraints
func AssertLocationConstraints(obj Location) error {
	return nil
}
